import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";

const inclusive = localFont({
  src: [
    {
      path: "./fonts/InclusiveSans-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/InclusiveSans-Medium.woff2",
      weight: "500",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${inclusive.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
